### ISSUE TITLE
`gh projects list --org xpiritbv` without a limit returns the options list

### ISSUE THREAD

**Issue by rajbos** [github/gh-projects#48] opened 2023-03-07 19:49 UTC
# Description 
Since the options state that the default is 100, I'd expect that this flag is optional: it is not.

# Expectation:
Default to 100 and continue

# Additional issue: 
Any number higher then 10 gives the options list, instead of working.

**Comment by mntlty** [comment] 2023-03-07 23:14
@rajbos thanks for the report? can you please include output when you run the command? I don't see the issue you're describing when I run the command, and don't see it marked as required in https://github.com/github/gh-projects/blob/main/cmd/list/list.go

```
$ gh projects list --org mntlty-org
Title                       Description  URL                                             ID
@mntlty's untitled project   -           https://github.com/orgs/mntlty-org/projects/XX  PVT_XXX
@mntlty's untitled project   -           https://github.com/orgs/mntlty-org/projects/XX PVT_XXX
my other project             -           https://github.com/orgs/mntlty-org/projects/X   PVT_XXX
```

**Comment by rajbos** [comment] 2023-03-08 08:31
Both inside and outside of a repo directory:
![image](https://user-images.githubusercontent.com/6085745/223662587-334f577a-cadf-4420-89f6-8c65d8b65b25.png)

**Comment by mntlty** [comment] 2023-03-08 18:45
@rajbos sorry for the frustrating experience!

The error you are seeing is due to an API error in processing the request, and is not part of the extension or the input parameters you put in.

The cli package that is used https://github.com/spf13/cobra shows the help output when it exits with a non-zero error code, which is the output you're seeing.

The relevant part in this case is the `Message` in the last line which indicates where it went wrong. You can also append `GH_DEBUG=api` to any CLI commands you run to get more verbose output and details.

I'm going to close this as the extension is working as intended.

**Closed by mntlty** 2023-03-08 18:45 UTC

**Comment by mntlty** [comment] 2023-03-09 06:51
@rajbos an api change went out which fixed the error - you should be able to run `gh projects list --org xpiritbv` without encountering that error
